### ISSUE TITLE
Error in applying crd.yaml

### ISSUE THREAD

**Issue by NarzeusNabartey** [chaos-mesh/chaos-mesh#1004]
Hi. I am trying to install this to our other Devtest Environment running with Openshift 3.9. However, i am having an error in installation.

<img width="1678" alt="Screen Shot 2020-09-30 at 2 15 53 PM" src="https://user-images.githubusercontent.com/53075732/94649751-e5445280-0327-11eb-9c55-3231a147f590.png">

My other installation was successful in Openshift 3.11 and my local env.

Many thanks,
Zeus

**Comment by zhouqiang-cl** [comment]
@yeya24 Could you please help to take a look

**Comment by Gallardot** [comment]
@NarzeusNabartey May be you can try this on Openshift 3.9
```
--feature-gates=CustomResourceValidation=false
```

refer [feature-gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/)

**Comment by yeya24** [comment]
I wouldn't say it is a bug because openshift 3.9 is too old. From what I can find one possible workaround is https://github.com/argoproj/argo-cd/issues/2423#issuecomment-539655175. Can you please take a look? 

You can manually install the CRD file https://github.com/chaos-mesh/chaos-mesh/blob/release-1.0/manifests/crd.yaml here.

**Comment by NarzeusNabartey** [comment]
Hi Team. I manually install the crd.yaml. I remove the validation part and it works. Thank you so much. We can close this now.
