### ISSUE TITLE
Can't login chaos-dashboard by token

### ISSUE THREAD

**Issue by cwen0** [chaos-mesh/chaos-mesh#1313]
## Bug Report

**What version of Kubernetes are you using?**

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-02-07T01:05:17Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
``` 

Chaos Mesh version: 

```
Controller manager Version: version.Info{GitVersion:"master-gb74b0e1ad5a032", GitCommit:"b74b0e1ad5a032950e160ead935ed754500525af", BuildDate:"2020-12-21T08:38:01Z", GoVersion:"go1.14.6", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you do?**
 

Login Chaos Dashboard by token 

**What did you expect to see?**

Login successfully

**What did you see instead?**

![image](https://user-images.githubusercontent.com/22956341/102775671-467c3f00-43c8-11eb-89d1-1823d795d9b6.png)
![image](https://user-images.githubusercontent.com/22956341/102775823-95c26f80-43c8-11eb-9db8-58df4398b713.png)

**Output of chaosctl**

**Comment by g1eny0ung** [comment]
Perhaps this is caused by different token formats in `localStorage`. In a certain historical submission, there was once a version that only supported single token mode (**But it was soon abandoned and now the latest code supports multiple tokens**). Because the two formats are stored in different ways, the `JSON.parse` method will be failed when you submit a new token in an upgraded dashboard.

If you encounter a situation where the token can't be submitted, you can check the token format in the `localStorage`.

The old format is a single token string, like `chaos-mesh-token:xxx` and the newest is like `chaos-mesh-token:[{"name":"test","token":"xxx"}]`

**The easiest solution is to delete the `chaos-mesh-token` field in `localStorage` and try to submit again.**
