### ISSUE TITLE
Latest v3.3 release still does not support different Service types for Dashboard Service

### ISSUE THREAD

**Issue by vovkanaz** [chaos-mesh/chaos-mesh#1327]
## Question

Hi there, the latest chaos-mesh-v0.3.3.tgz of the HELM chart does not support this functionality [Link](https://github.com/chaos-mesh/chaos-mesh/blob/master/helm/chaos-mesh/templates/chaos-dashboard-deployment.yaml ) which has been fixed in -->  [Link](https://github.com/chaos-mesh/chaos-mesh/pull/1042). Would you mind to push the latest changes to the helm chart repository? Thanks in advance.

**Comment by g1eny0ung** [comment]
I think because this change hasn't been merged into the `v1.0` branch, it won't take effect in `chart-0.3.3`.

Because every chart release usually represents a stable version so the changes on the master will be released in the next minor version (at least).

We already have a plan to release the next minor version (v1.1.0) at the end of December. Thx for the follow-up.~
