### ISSUE TITLE
chaos target support more than one container

### ISSUE THREAD

**Issue by WangXiangUSTC** [chaos-mesh/chaos-mesh#1354]
## Feature Request

**Is your feature request related to a problem? Please describe:**
https://github.com/chaos-mesh/chaos-mesh/issues

**Describe the feature you'd like:**

Now can only choose one container in Pod to inject chaos, need to support specify more than one container.

**Comment by DarthBenro008** [comment]
Hey There!
I have noticed currently Chaos-Mesh takes in only a single container name in spec, the first container if none is mentioned in spec otherwise whatever ContainerName is mentioned in the spec

https://github.com/chaos-mesh/chaos-mesh/blob/6d045300ab546a60ac2ba6896032eb9331fb24cb/controllers/stresschaos/types.go#L191-L204

For this feature to be implemented, are we planning to just inject the stressors into all containers (a Boolean in the YAML configs)? or allow the user to specify a set of Container Names? (maybe an array of container names in YAML)

I would like to work on this issue 😄

**Comment by WangXiangUSTC** [comment]
Thanks! I think we can implement these two features: 1. inject into all containers 2. specify a set of container names
@cwen0 @YangKeao @zhouqiang-cl @STRRL  how about you?

**Comment by YangKeao** [comment]
> For this feature to be implemented, are we planning to just inject the stressors into all containers

Wow, really cool :beers: ! Some of these chaos are container-wise (like `StressChaos` and `IOChaos`) and some of them are pod-wise (like `NetworkChaos`). Could we have a unified way to call the implementation of them (rather than calling `SelectPods` or `SelectContainers` in the `Apply` functions.)

**Comment by DarthBenro008** [comment]
@YangKeao maybe we could have a utility function, which takes in 3 parameters
- `Pod Name`
- `Type of Chaos to be injected`
- `List of Container names`

Then that function can apply that particular chaos to the required containers.
This util function can maybe be called from `types.go` of each Chaos Type that you had mentioned above.

**Comment by YangKeao** [comment]
This issue has been fixed since June. Every chaos in container scope is selected with `containerNames: []string` to select multiple containers at the same time :smiley:.
