### ISSUE TITLE
Fail to deploy Chaos Mesh caused by enabling `HostIPC`, `HostPID`, and `HostPath`

### ISSUE THREAD

**Issue by cwen0** [chaos-mesh/chaos-mesh#1517]
## Bug Report

**What version of Chaos Mesh are you using?**
 

v1.1.1

**What did you do?**
 

Use `helm template` command to generate some YAML files and then apply them. 

**What did you expect to see?** 

Install Chaos Mesh successfully. 

**What did you see instead?** 

```
Exception ( Monitor Deploy )
Deploy failed: Error from server ([denied by policy-host-namespaces] DaemonSet cannot use hostIPC: xxxx/chaos-daemon [denied by policy-host-namespaces] DaemonSet cannot use hostPID: xxxx/chaos-daemon [denied by policy-additional-capabilities] DaemonSet cannot add capabilities: xxxx/chaos-daemon - chaos-daemon [denied by policy-host-path] DaemonSet cannot use hostPath: xxxx/chaos-daemon - container chaos-daemon uses volume socket-path [denied by policy-host-path] DaemonSet cannot use hostPath: xxxx/chaos-daemon - container chaos-daemon uses volume sys-path): error when creating "STDIN": admission webhook "validation.gatekeeper.sh" denied the request: [denied by policy-host-namespaces] DaemonSet cannot use hostIPC: xxxx/chaos-daemon [denied by policy-host-namespaces] DaemonSet cannot use hostPID: xxxx/chaos-daemon [denied by policy-additional-capabilities] DaemonSet cannot add capabilities: xxxx/chaos-daemon - chaos-daemon [denied by policy-host-path] DaemonSet cannot use hostPath: xxxx/chaos-daemon - container chaos-daemon uses volume socket-path [denied by policy-host-path] DaemonSet cannot use hostPath: xxxx/chaos-daemon - container chaos-daemon uses volume sys-path
```

**Output of chaosctl**

**Comment by STRRL** [comment]
It seems "gatekeeper" reject these operations.

Because open-agent-policy gatekeeper uses "rego" to describe their security rule, and generate CRD "constraints template" dynamically, it's so flexible that we could not give a stable solution, it depends on the adopter's customized security rule.

But making an exception rule on namespace might work, here is a reference about this: https://open-policy-agent.github.io/gatekeeper/website/docs/exempt-namespaces/

Still waiting for the response of our adopter.
