### ISSUE TITLE
io-delay experiment causes read error from specified volumePath and as consequence  PostgreSQL restart

### ISSUE THREAD

**Issue by alelerac** [chaos-mesh/chaos-mesh#2626]
## Bug Report

**What version of Kubernetes are you using?**

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"ec2760d6d916781de466541a6babb4309766c995", GitTreeState:"clean", BuildDate:"2021-02-27T17:18:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

**What version of Chaos Mesh are you using?**

Controller manager Version: version.Info{GitVersion:"v2.1.0", GitCommit:"802bf850e3e852b2aecc88400f9b5c66cfab9e9c", BuildDate:"2021-11-30T12:32:19Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}

**What did you do?**

Starting io-delay experiment on statefulset pod
kubectl apply io-delay.yaml 

content of io-delay.yaml file:
apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: io-delay-database-pg
  namespace: robust
spec:
  action: latency
  mode: one
  selector:
    labelSelectors:
      "statefulset.kubernetes.io/pod-name": database-pg-1
  volumePath: /var/lib/postgresql/data 
  delay: "1ms"
  percent: 100
  duration: "50s"

**What did you expect to see?**

I am expecting to see read/write delays from specified volumePath.

**What did you see instead?**

Application running in container can not read file "postmaster.pid" as soon as io-delay is started. 

shell script added to container under test and executes "cat postmaster.pid" in volumePath /var/lib/postgresql/data/ every second.
cat  postmaster.pid returns error " No such file or directory" after starting  io-delay with 
kubectl apply -f io-delay.yaml

Output from shell script:

Iteration number:  15 
path: /var/lib/postgresql/data/pgdata/ 
command:  cat postmaster.pid

data dir at: 18:20:29
23994
/var/lib/postgresql/data/pgdata
1639073914
5432
/tmp
*
   131075    196609
ready   

>>>>>>   CHAOS IO-DELAY  STARTED <<<<

Iteration number:  16 
path: /var/lib/postgresql/data/pgdata/ 
command:  cat postmaster.pid

data dir at: 18:20:30
cat: postmaster.pid: No such file or directory   < === ERROR

Iteration number:  17 
path: /var/lib/postgresql/data/pgdata/ 
command:  cat postmaster.pid

data dir at: 18:20:31
cat: postmaster.pid: No such file or directory  < === ERROR

Additional information:
If the shell script uses absolute path name so "cat /var/lib/postgresql/data/pgdata/postmaster.pid"
the file postmaster.pid is readable during experiment and error "No such file or directory" is not received.

**Output of chaosctl**

./chaosctl debug iochaos -n chaos-testing
I1209 20:19:58.463484   18267 request.go:668] Waited for 1.015053911s due to client-side throttling, not priority and fairness, request: GET:https://access-n16vpod2-adp3634-ipv4.sero.gic.ericsson.se/k8s/clusters/c-hw955/apis/security.istio.io/v1beta1?timeout=32s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x18a71e5]

goroutine 1 [running]:
github.com/chaos-mesh/chaos-mesh/api/v1alpha1.(*ChaosKind).SpawnList(...)
	/home/user1/app/chaos-mesh/api/v1alpha1/kinds.go:95
github.com/chaos-mesh/chaos-mesh/pkg/chaosctl/common.GetChaosList(0x1f620b8, 0xc0000a7f80, 0xc0006c6e39, 0x7, 0x0, 0x0, 0x7fffa60d4630, 0xd, 0x1f78318, 0xc0001c4700, ...)
	/home/user1/app/chaos-mesh/pkg/chaosctl/common/common.go:224 +0xc5
github.com/chaos-mesh/chaos-mesh/pkg/chaosctl/cmd.(*DebugOptions).Run(0xc0004e9c80, 0x1cf5ee8, 0x7, 0xc0004e4f40, 0x0, 0x2, 0xc0005a6600, 0x0, 0x0)
	/home/user1/app/chaos-mesh/pkg/chaosctl/cmd/debug.go:180 +0x13b
github.com/chaos-mesh/chaos-mesh/pkg/chaosctl/cmd.NewDebugCommand.func5(0xc0004f4000, 0xc0004e4f40, 0x0, 0x2, 0x0, 0x0)
	/home/user1/app/chaos-mesh/pkg/chaosctl/cmd/debug.go:131 +0xa5
github.com/spf13/cobra.(*Command).execute(0xc0004f4000, 0xc0004e4f20, 0x2, 0x2, 0xc0004f4000, 0xc0004e4f20)
	/home/user1/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x2bc2bc0, 0xc0005dbec8, 0x1, 0x1)
	/home/user1/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/user1/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/chaos-mesh/chaos-mesh/pkg/chaosctl/cmd.Execute()
	/home/user1/app/chaos-mesh/pkg/chaosctl/cmd/root.go:80 +0x675
main.main()
	/home/user1/app/chaos-mesh/cmd/chaosctl/main.go:21 +0x25

kubectl describe iochaos ...  is not showing any error/warning
  Type    Reason           Age    From          Message
  ----    ------           ----   ----          -------
  Normal  FinalizerInited  2m17s  finalizer     Finalizer has been inited
  Normal  Started          2m17s  desiredphase  Experiment has started
  Normal  Updated          2m17s  finalizer     Successfully update finalizer of resource
  Normal  Updated          2m17s  desiredphase  Successfully update desiredPhase of resource
  Normal  Updated          2m16s  records       Successfully update records of resource
  Normal  Updated          2m16s  records       Successfully update records of resource
  Normal  Updated          2m15s  records       Successfully update records of resource
  Normal  Applied          2m15s  records       Successfully apply chaos for robust/database-pg-1/database-pg
  Normal  TimeUp           87s    desiredphase  Time up according to the duration
  Normal  Updated          87s    desiredphase  Successfully update desiredPhase of resource
  Normal  Updated          87s    records       Successfully update records of resource
  Normal  Recovered        87s    records       Successfully recover chaos for robust/database-pg-1/database-pg
  Normal  Updated          87s    records       Successfully update records of resource

**Comment by YangKeao** [comment]
@alelerac Sorry for the late rely. I eventually have some time to work on this issue 😢. This afternoon I tried to setup a postgresql-14 container, and injected IOChaos into it. The default data path is `/var/lib/postgresql/data` and the workload is sysbench oltp read write.

However, the result is that it works fine. Do you have any customized configuration for postgresql? (e.g. set the data directory to `/var/lib/postgresql/data`)

But while doing this attempt, I found that the current work directory has corrupted. For example: if a `bash` was inside the `/var/lib/postgresql/data/SOME` (which is an empty directory created manually), after injected,  running `ls` in this directory will see all files under `/var/lib/postgresql/data` (but not `/var/lib/postgresql/data/SOME`), and the `pwd` of it will still return `/var/lib/postgresql/data/SOME`.

This confusing behavior can be reproduced simply: 

1. Start a ubuntu container, mount folder `/var/lib/postgresql/data`. `docker run -it --rm -v SOME_PATH:/var/lib/postgresql/data ubuntu /bin/bash`
2. Create several files and a folder under the volume: `touch a && touch b && touch c && mkdir some`
3. Enter the `some` directory, create a file `cd some && touch d`
3. Execute toda with nsexec manully: `sudo nsexec -l -m /proc/213792/ns/mnt -p /proc/213792/ns/pid -i /proc/213792/ns/ipc ./target/release/toda --path /var/lib/postgresql/data`
4. Run `ls -lah`, you will see `a,b,c` 😢 

A more confusing problem is that, you can execute `cd .`, and then `ls -lah`, the result will be `d` 😅 . I guess the problem is inside the cwd replacer of `toda`. I will fix it soon.


However, I don't know whether this bug fix could solve the problem described in this issue, as I cannot reproduce the same problem under postgresql. I will also try to set the data directory of postgresql to a subdirectory of the volume later.

**Comment by YangKeao** [comment]
I tried to set `-e PGDATA=/var/lib/postgresql/data` for a postgresql container, and this bug is reproduced successfully! And I also checked that #2747 would fix this issue. The next bugfix version (for both 2.0 and 2.1) will fix this bug.

**Comment by kfaseela** [comment]
@YangKeao : Do we have a release already with this fix?
