### ISSUE TITLE
Refactor Request - Daemonset ENV options instead of flags

### ISSUE THREAD

**Issue by craig-seeman** [chaos-mesh/chaos-mesh#2743]
## Question

Hello! 😄 

While implementing a PR I noted that there is a difference between how the daemon and the controller-manager configurations are loaded. The dashboard and controller-manager both use ENV variables, while the daemon uses command-line flags.

I am wondering, is there a standard that could be agreed upon for controller-manager, daemon and dashboard to always load config variables from ENV variables and not the command-line `binary --someconfig value`? Given some of the 'ease' of using environment variables and comment here that they are more widely used https://github.com/chaos-mesh/chaos-mesh/issues/2734#issuecomment-1003249700 with defaults in the codebase, would it be a good idea to change the daemon from using command-line flags to environment variables?

When using smaller applications such as nsexec, experiment attacks, etc it is obviously much easier to have command-line flags, so those could/should remain the same.

Estimated changes needed:
Refactor in daemon settings
Refactor in daemon Helm definitions

**Comment by WangXiangUSTC** [comment]
I think the reason for adding command-line flags for chaos-daemon is that could deploy on physical machines, not just on K8s. @YangKeao Could you please explain why do it this way?

**Comment by YangKeao** [comment]
> Could you please explain why do it this way?

I think we haven't considered too much when staring the `chaos-daemon`.

IMO, it would be great to change the daemon from using command-line flags to environment variables (with the help of `envconfig`). The configuration of chaos daemon is not complicated, @craig-seeman would you like to do this refractor for Chaos Mesh?

Another problem is the compatibility. Upgrading through the `helm` don't have any problem, as we will not modify the helm values file, and the configuration is persistent by helm (in a `secret`, or `configmap`, [etc](https://helm.sh/docs/topics/advanced/#storage-backends)). However, there are actually some users using pure yaml files to install the Chaos Mesh, and this modification needs a manual migration. @cwen0 @STRRL  What's your opinion?

BTW, in the long term, I have considered using [`viper`](https://github.com/spf13/viper) to manage the configuration, so that, the command-line arguments, the environment variables and the config files can work together, but it seems to be a complicated work 😢 . (IMO, environment variables and configuration files have their own pros and cons, and I cannot decide which one is better).

**Comment by STRRL** [comment]
> However, there are actually some users using pure yaml files to install the Chaos Mesh, and this modification needs a manual migration.

I have no idea about it, we do not maintain pure yaml files and we could not make any guarantee on them. I think we could only provide limited support if users open an issue about their migration.

And how about using `viper` instead of `envconfig` from now?  🤣🤣🤣
