### ISSUE TITLE
Using GitHub Actions, approach to chaos-mesh installation

### ISSUE THREAD

**Issue by Jorge-Zed** [chaos-mesh/chaos-mesh#2980]
## Question

Hello team,

We have been testing the use of Github Actions to run experiments and we spotted an issue that would like to ask about to understand what is your approach to it.

First time we run our workflow it works perfectly fine, chaos-mesh gets installed and it applies the selected experiments.

We found that the 2nd time we run our github workflow, we receive an error because the namespace already exist:
```
customresourcedefinition.apiextensions.k8s.io/iochaos.chaos-mesh.org configured
customresourcedefinition.apiextensions.k8s.io/kernelchaos.chaos-mesh.org configured
customresourcedefinition.apiextensions.k8s.io/networkchaos.chaos-mesh.org configured
customresourcedefinition.apiextensions.k8s.io/podchaos.chaos-mesh.org configured
customresourcedefinition.apiextensions.k8s.io/podiochaos.chaos-mesh.org configured
customresourcedefinition.apiextensions.k8s.io/podnetworkchaos.chaos-mesh.org configured
customresourcedefinition.apiextensions.k8s.io/stresschaos.chaos-mesh.org configured
customresourcedefinition.apiextensions.k8s.io/timechaos.chaos-mesh.org configured
Error from server (AlreadyExists): namespaces "chaos-testing" already exists
```

We want to understand what is your approach to this. We found that uninstalling chaos-mesh at the end of the workflow might be an issue in case you would like to schedule experiments that might run in a later time.

**Comment by dcalvin** [comment]
@WangXiangUSTC @cwen0 PTAL

**Comment by iguoyr** [comment]
Hi @Jorge-Zed, could you show a part of the config file of this github action? Do you install Kubernetes in your action every time? It seems that Kubernetes is already exist before the 2nd time.

**Comment by iguoyr** [comment]
Hi @dcalvin, I want to figure out a question, `1st time` and `2nd time` means running a workflow multi times, or calling `chaos-mesh/chaos-mesh-action@master` multi times in one workflow?

1. if it means running a workflow multi times, I think the problem is related with the approach of installing Kubernetes, it need a clean Kubernetes cluster before calling `chaos-mesh/chaos-mesh-action@master`, you could use [Kind Cluster](https://github.com/marketplace/actions/kind-cluster) or [Kind Action](https://github.com/marketplace/actions/kind-kubernetes-in-docker-action) to deploy Kubernetes in your workflow.
2. if it means calling `chaos-mesh/chaos-mesh-action@master` multi times in one workflow, maybe you could refer to [this example](https://github.com/pingcap/dm/blob/master/.github/workflows/chaos-mesh.yml#L264).
