### ISSUE TITLE
 Failed to apply chaos: It's dangerous to inject network chaos on a pod(7c8f65449-kxsxs) with `hostNetwork`

### ISSUE THREAD

**Issue by dongbaolei** [chaos-mesh/chaos-mesh#3158]
## Bug Report

![image](https://user-images.githubusercontent.com/17330046/163949439-df443062-c9a3-494e-a53f-a55a4c23ee28.png)

**Comment by YangKeao** [comment]
Chaos Mesh doesn't allow to inject network chaos for a pod with host network, because it may affect other programs on the same machine (include the Chaos Mesh itself, which will make it unrecoverable). This protection can be removed by setting `controllerManager.allowHostNetworkTesting` to true, but it's **dangerous**.
