### ISSUE TITLE
New minimum supported kubernetes version as kubernetes 1.19

### ISSUE THREAD

**Issue by STRRL** [chaos-mesh/chaos-mesh#3169]
previous: https://github.com/chaos-mesh/chaos-mesh/issues/1886

Kubernetes 1.15 became EOL at 2020, May (2 years ago). 

Keeping the support for the old Kubernetes version would lead to more cost on maintenance compatibility codes.

We should decide the next minimum supported Kubernetes version.

**Comment by STRRL** [comment]
I propose using Kubernetes 1.19 as the minimum supported kubernetes version in 2.3.0.

PTAL  @chaos-mesh/maintainers @chaos-mesh/committers 

refer:

supported Kubernetes version on cloud providers:

- AWS: 1.19  https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html
- Azure AKS: N-3 Version(1.21 now) https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#faq
- GCP: 1.21 (14-month support) https://cloud.google.com/kubernetes-engine/versioning#version-support
- Kubernetes release timeline: https://en.wikipedia.org/wiki/Kubernetes#Release_timeline

**Comment by STRRL** [comment]
I think this enhancement would NOT be carried with 2.3.0, because we only have a few days.

I would update the milestone.

**Comment by YangKeao** [comment]
Off-topic: I found the behavior of installing chaos mesh on unsupported old version of kubernetes is quite interesting. For example, if you are installing the Chaos Mesh on kubernetes 1.11, whose CRD doesn't support default value, then the `.spec.percent` in `IOChaos` is default to 0, which means no io injection will take place.

(But it doesn't matter, because 1.11 is too old, and we'll definitely not support it :smile: )
