### ISSUE TITLE
Offline installation of the chaos-deamon keeps rebooting!

### ISSUE THREAD

**Issue by S972776051** [chaos-mesh/chaos-mesh#3285]
![5a117dc50a2e5aa1fa72eb624c57095](https://user-images.githubusercontent.com/65998909/169760669-53069f1d-0135-44a5-b5b7-a8252f6fae4f.jpg)
添加这条命令后，不会重复启动，可以正常访问web页面，但是实验有影响，请问是因为deamon没有正确启动吗？

**Comment by YangKeao** [comment]
It seems to cause the https://github.com/chaos-mesh/chaos-mesh/issues/3263#issuecomment-1135460055 . This line doesn't start  the chaos-daemon. Could you attach the log without this line?

---

这看起来就是 https://github.com/chaos-mesh/chaos-mesh/issues/3263#issuecomment-1135460055 中报错的原因了，因为它之后的 ca 配置没有读进去。

现在需要解决的问题是没有这一行为什么会不停重复启动。能够在不加这一行的情况下获取 chaos-daemon 的日志并贴在这里呢？

**Comment by S972776051** [comment]
> 它似乎导致了[#3263 (comment)](https://github.com/chaos-mesh/chaos-mesh/issues/3263#issuecomment-1135460055)。此行不会启动混沌守护进程。你能附上没有这条线的日志吗？
> 
> 这看起来就是 [#3263 (comment)](https://github.com/chaos-mesh/chaos-mesh/issues/3263#issuecomment-1135460055) 中报错的原因了，因为它之后的 ca 配置没有读进去。
> 
> 现在需要解决的问题是没有这一行为什么会不停重复启动。能够在不加这一行的情况下获取 chaos-daemon 的日志并贴在这里呢？
![286398bc5b1b66655df8e1101057d12](https://user-images.githubusercontent.com/65998909/170026421-00a37de4-ded2-49ff-a8a5-1b27165e34f7.jpg)
![e0d367758e90b84327a5958d937755b](https://user-images.githubusercontent.com/65998909/170026437-631f1f1c-ebf3-43f3-8f99-7efca08dcc18.jpg)

**Comment by S972776051** [comment]
What other logs do you need? This problem has been delayed for a long time. I hope it can be solved

**Comment by S972776051** [comment]
i saw (
Chaos Mesh does not support using different Container Runtimes in one cluster.

Because we only use one daemonset for bootstrapping chaos-daemon.

I think manually set up chaos-daemon for different nodes with the proper configuration could resolve that.)

How to realize it？

**Comment by YangKeao** [comment]
> > 它似乎导致了[#3263 (comment)](https://github.com/chaos-mesh/chaos-mesh/issues/3263#issuecomment-1135460055)。此行不会启动混沌守护进程。你能附上没有这条线的日志吗？
> > 这看起来就是 [#3263 (comment)](https://github.com/chaos-mesh/chaos-mesh/issues/3263#issuecomment-1135460055) 中报错的原因了，因为它之后的 ca 配置没有读进去。
> > 现在需要解决的问题是没有这一行为什么会不停重复启动。能够在不加这一行的情况下获取 chaos-daemon 的日志并贴在这里呢？
> > ![286398bc5b1b66655df8e1101057d12](https://user-images.githubusercontent.com/65998909/170026421-00a37de4-ded2-49ff-a8a5-1b27165e34f7.jpg)
> > ![e0d367758e90b84327a5958d937755b](https://user-images.githubusercontent.com/65998909/170026437-631f1f1c-ebf3-43f3-8f99-7efca08dcc18.jpg)

Oh! I understand the problem! You are using the latest helm chart (v2.2.0) to install the older version (v2.1.5), so the binary doesn't have the flag.

So there are two ways to solve the problem:

1. Use the latest image, download `ghcr.io/chaos-mesh/...:v2.2.0` instead of `v2.1.5`
2. Use the older helm chart, `helm install ..... --version 2.1.5`

(I think the problem occurs because we haven't published the document of v2.2.0 after it released, and the document of the older version needs some modification)

> i saw (
> Chaos Mesh does not support using different Container Runtimes in one cluster.

> Because we only use one daemonset for bootstrapping chaos-daemon.

> I think manually set up chaos-daemon for different nodes with the proper configuration could resolve that.)

> How to realize it？

This is totally a different problem, and it's hard to describe in a short term. You'll need to create multiple chaos-daemon (one for each node, with `nodeSelector` to lock them on the node), and set proper command line flag for the chaos-daemon.

For version before v2.2.0, you'll need to set the `--runtime` to be the one you use (`docker`, `containerd` or `crio`), and mount the container runtime socket (like `/var/run/crio/crio.sock`) to the `/var/run/docker.sock` inside the container.

For version after v2.2.0, you'll need to set the `--runtime` to be the one you use (`docker`, `containerd` or `crio`), and mount the container runtime socket (like `/var/run/crio/crio.sock`) to any location inside the container (assume it's `C_PATH`), then set the `--runtime-socket-path` to be `C_PATH`.

I suggested to solve the first problem and check it works, then try to do the following settings :crying_cat_face: . If you could understand the go template language, you could take a look at our `DaemonSet` configuration for an example https://github.com/chaos-mesh/chaos-mesh/blob/release-2.1/helm/chaos-mesh/templates/chaos-daemon-daemonset.yaml (take care of the branch and version)

**Comment by S972776051** [comment]
> 

谢谢 大哥，我爱你

**Comment by S972776051** [comment]
> > > 它似乎导致了[#3263 (comment)](https://github.com/chaos-mesh/chaos-mesh/issues/3263#issuecomment-1135460055)。此行不会启动混沌守护进程。你能附上没有这条线的日志吗？
> > > 这看起来就是 [#3263 (comment)](https://github.com/chaos-mesh/chaos-mesh/issues/3263#issuecomment-1135460055) 中报错的原因了，因为它之后的 ca 配置没有读进去。
> > > 现在需要解决的问题是没有这一行为什么会不停重复启动。能够在不加这一行的情况下获取 chaos-daemon 的日志并贴在这里呢？
> > > ![286398bc5b1b66655df8e1101057d12](https://user-images.githubusercontent.com/65998909/170026421-00a37de4-ded2-49ff-a8a5-1b27165e34f7.jpg)
> > > ![e0d367758e90b84327a5958d937755b](https://user-images.githubusercontent.com/65998909/170026437-631f1f1c-ebf3-43f3-8f99-7efca08dcc18.jpg)
> 
> 哦！我明白这个问题！您正在使用最新的 helm chart (v2.2.0) 安装旧版本 (v2.1.5)，因此二进制文件没有标志。
> 
> 所以有两种方法可以解决这个问题：
> 
> 1. 使用最新的图像，下载`ghcr.io/chaos-mesh/...:v2.2.0`而不是`v2.1.5`
> 2. 使用较旧的舵图，`helm install ..... --version 2.1.5`
> 
> （我认为问题的出现是因为v2.2.0发布后我们还没有发布文档，老版本的文档需要修改）
> 
> > 我看到了（
> > 混沌网格不支持在一个集群中使用不同的容器运行时。
> 
> > 因为我们只使用一个 daemonset 来引导 Chaos-daemon。
> 
> > 我认为通过正确的配置为不同的节点手动设置 Chaos-daemon 可以解决这个问题。）
> 
> > 如何实现？
> 
> 这是一个完全不同的问题，很难在短期内描述。您需要创建多个混沌守护进程（每个节点一个，`nodeSelector`并将它们锁定在节点上），并为混沌守护进程设置正确的命令行标志。
> 
> 对于 v2.2.0 之前的版本，您需要将 设置为`--runtime`您使用的那个（`docker`或`containerd`）`crio`，并将容器运行时套接字（如`/var/run/crio/crio.sock`）安装到容器`/var/run/docker.sock`内部。
> 
> 对于 v2.2.0 之后的版本，您需要将 设置为`--runtime`您使用的（`docker`或`containerd`）`crio`，并将容器运行时套接字（如`/var/run/crio/crio.sock`）安装到容器内的任何位置（假设它是`C_PATH`），然后将 设置`--runtime-socket-path`为`C_PATH`.
> 
> 我建议解决第一个问题并检查它是否有效，然后尝试进行以下设置😿. 如果你能理解 go 模板语言，你可以看看我们的`DaemonSet`配置示例[https://github.com/chaos-mesh/chaos-mesh/blob/release-2.1/helm/chaos-mesh/templates/ chaos-daemon-daemonset.yaml](https://github.com/chaos-mesh/chaos-mesh/blob/release-2.1/helm/chaos-mesh/templates/chaos-daemon-daemonset.yaml)（照顾分支和版本）

谢谢  大哥  永远的神  我爱你！

**Comment by YangKeao** [comment]
Then I will close this issue and https://github.com/chaos-mesh/chaos-mesh/issues/3263#issuecomment-1135460055. If you still face any problem, or need some further discussion, feel free to reopen or create a new issue.

---

既然问题已经解决 :beers: ，我会把这个 issue 和  https://github.com/chaos-mesh/chaos-mesh/issues/3263 关掉。如果你在使用 Chaos Mesh 的过程中遇到了任何其它的问题（或对我们有任何建议），随时可以建立一个新 Issue :smiley_cat: .
