### ISSUE TITLE
PhysicalMachineChaos on New Workflow: spec.mode: Unsupported value: ""

### ISSUE THREAD

**Issue by cwen0** [chaos-mesh/chaos-mesh#3747]
## Bug Report

**What version of Kubernetes are you using?**

**What version of Chaos Mesh are you using?**

v2.4.1 

**What did you do? / Minimal Reproducible Example**
 

Create a PhysicalMachineChaos on New Workflow

**What did you expect to see?** 

All is OK

**What did you see instead?** 

![image](https://user-images.githubusercontent.com/22956341/199876660-971931d4-8df5-4d35-b07b-d4b5f4f99da4.png)

**Output of chaosctl**

**Comment by cwen0** [comment]
@g1eny0ung PTAL

**Comment by g1eny0ung** [comment]
After I checked, the item in this line should be optional, right? Since we still support the `address` field.

https://github.com/chaos-mesh/chaos-mesh/blob/9d174215eed80794b0fd13cf9c655b23ccef55a0/api/v1alpha1/physical_machine_chaos_types.go#L128

So part of the logic related here should be updated.

**Comment by g1eny0ung** [comment]
I mean if the user using the `address` field, then the `mode` is not required?

**Comment by g1eny0ung** [comment]
I mean if the user using the `address` field, then the `mode` is not required?

**Comment by g1eny0ung** [comment]
> I mean if the user using the `address` field, then the `mode` is not required?

Oh, got it. I realized that mode can also work on the address field.
