### ISSUE TITLE
chaos-dns-server does not expose metrics while it mentions prometheus port

### ISSUE THREAD

**Issue by fzyzcjy** [chaos-mesh/chaos-mesh#4117]
## Bug Report

**What version of Kubernetes are you using?**

1.25

**What version of Chaos Mesh are you using?**

latest

**What did you do? / Minimal Reproducible Example**

check chaos-dns-server 

**What did you expect to see?**
prometheus metrics

**What did you see instead?**
that port does not expose anything, even connection refused

**Output of chaosctl**

**Comment by WeAreHadock** [comment]
Hey, 

Any update on this issue ?
The dns-server service has annotations like `prometheus.io/port: "9153"` (https://github.com/chaos-mesh/chaos-mesh/blob/master/helm/chaos-mesh/templates/dns-service.yaml#L23C33-L23C33) but it doesn't expose anything

**Comment by dvinayakkumar** [comment]
The annotation `prometheus.io/port: "9153"` does not expose metrics on port 9153. It only tells Prometheus that this is the port where metrics are already available. To pin point where the issue was, do these

1. Do a curl request from within the cluster on the endpoint where the metrics are expected. For example: curl http://<k8s-svc-url>:<port>/metrics. If you see metrics as the output, there is an issue with Prometheus setup or its auto discovery function. Make sure the place from where you are doing curl request has access to reach the service url.
2. If you do not see metrics in the above step, check the component of the application which exposes these metrics.

However I believe it is better to place annotations on pod level (in Daemonset kubernetes file, in template section). Once you figure out whether issue in on Prometheus side (scraping side) or application side (exposing side), we can start debug further. 

Thank you,
Vinayak.

**Comment by enneitex** [comment]
Hi,

The issue here is that chaos-dns-server doesn't expose metrics (at least not on port 9153) but the annotation is hardcoded in [the template](https://github.com/chaos-mesh/chaos-mesh/blob/master/helm/chaos-mesh/templates/dns-service.yaml#L23C33-L23C33) so prometheus is trying to scrape an endpoint that doesn't work.

Is the chaos-dns-server supposed to expose prometheus metrics ? If not I can submit a PR to remove those annotations from the service template

**Comment by tboerger** [comment]
That's right, the annotations are hard-coded within the helm chart and the Corefile that gets used by the helm chart is lacking the [prometheus directive](https://coredns.io/plugins/metrics/): https://github.com/chaos-mesh/chaos-mesh/blob/master/helm/chaos-mesh/templates/dns-configmap.yaml

With the current hard-coded values my alertmanager is fireing all the time because the exporter is not up and can't ever get up as long as there are wrong values hard-coded.

**Comment by tboerger** [comment]
Within https://github.com/chaos-mesh/chaos-mesh/pull/4321 I have simply added the `prometheus` directive. That should resolve the issue with the next release after it's getting merged.
