### ISSUE TITLE
Complete the guide about how to observe the result of stress chaos

### ISSUE THREAD

**Issue by yeya24** [chaos-mesh/chaos-mesh#468]
## Feature Request

Now we already have a document about stress chaos https://github.com/pingcap/chaos-mesh/blob/master/doc/stress_chaos.md, however, this document doesn't tell much about how to observe the result of CPU stress and Memory stress.

It would be much clear to users if we can enrich the document with the observation part.

**Comment by yeya24** [comment]
Still valid.

**Comment by YangKeao** [comment]
I am working on #685 (actually it's waiting for review), so that users can observe the `stress-ng` process easily by `htop` or `ps`.

But I think the document is still needed, because in the parent process of `stress-ng` will be PID 0 in the container, so `htop` will regard it as "kernel threads" and will not show by default. The users have to turn off "hide kernel threads" to see these process.
